### ISSUE TITLE
Update to Polymer 1.x?

### ISSUE THREAD

**Issue by moderndeveloperllc** [zedesk/zdk-agenda#3]
Just curious if you were planning on updating this to 1.x at some point in time, or if this was just an experiment that's archived?

**Comment by zedesk** [comment]
Hi,

Yes I plan to update the component to 1.x, but it will certainly be a
complete rewrite as it's not very optimized.

**Comment by isabelacmor** [comment]
Hi there!

I've forked this repo and begun working on a 1.0 port. It may be a bit hacky, but it's a start. I haven't fully tested everything, but the initial commit mirrors the 0.5 version along with all the functionality I could find (couldn't figure out event clicks on the 0.5 version, so it's not in the 1.0 port).

https://github.com/isabellacmor/zdk-agenda/tree/polymer1.0
